#!/bin/bash

echo "                   cedr version 0.2"
echo "          running on upstream crouton ae59434"
echo "                created by @rainestorme"
echo
echo "cedr is an early POC, don't use it for anything important."
